Class dc.iris.mail.Production Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="dc.iris.mail.Production" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="Mail Service" Category="" ClassName="dc.iris.mail.Service" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}
